blog/article/urls.py
from django.urls import path
from article import views


app_name = 'article'
urlpatterns = [
    path('', views.article, name='article'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls', namespace='article')),
    path('main/', include('main.urls', namespace='main')),
    re_path('.*', views.main),
]

blog/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
]

blog/article/models.py
from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-pubDateTime']



class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.article.title + '-' + str(self.id)
    
    class Meta:
        ordering = ['pubDateTime']

blog/article/views.py
from django.shortcuts import render

from article.models import Article


def article(request):
    '''
    Render the article page
    '''
    
    articles = Article.objects.all()
    context = {'articles':articles}
    return render(request, 'article/article.html', context)

blog/main/views.py
from django.shortcuts import render



def main(request):
    '''
    Show 'Hello world!' in the main page
    '''
    context = {'like':'Django 很棒'}
    return render(request, 'main/main.html', context)
    
def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')

blog/article/templates/article/article.html
{% extends 'main/base.html' %}
{% block heading %}歡迎蒞臨{% endblock %}
{% block content %}
<br>
{% for article in articles %}
  <h3>{{ article.title }}</h3>
  <p>發表時間：{{ article.pubDateTime|date:'Y-m-d H:i' }}</p>
  <div class="articleContent">{{ article.content|linebreaks}}</div>
  <hr>
{% endfor %}
{% endblock %}

blog/main/templates/main/about.html
{% extends 'main/base.html' %}
{% block heading %}關於{% endblock %}
{% block content %}
<p>歡迎來到我的部落格，您可盡情瀏覽並留言。</p>
{% endblock %}

blog/main/templates/main/base.html
<!doctype html>
{% load static %}
<html>
<head>
<title>部落格</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
{% include 'main/menu.html' %}
<h2>部落格 -- {% block heading %}{% endblock %}</h2>
{% block content %}{% endblock %}
</body>
</html>

blog/main/templates/main/main.html
{% extends 'main/base.html' %}
{% block heading %}首頁{% endblock %}
{% block content %}
<p>{{ like }}</p>
{% endblock %}

blog/main/templates/main/menu.html
<ul id="menu">
  <li><a href="{% url 'main:main' %}">首頁</a></li>
  <li><a href="{% url 'main:about' %}">關於</a></li>
    <li><a href="{% url 'article:article' %}">部落格</a></li>
</ul>